packages:
  - playground

catalog:
  # Vue ecosystem
  vue: ^3.5.26
  '@vitejs/plugin-vue': ^6.0.3

  # Build tools
  vite: ^7.3.1
  typescript: ^5.9.3
  tsdown: ^0.18.4

  # CodeMirror
  '@codemirror/lang-css': ^6.3.1
  '@codemirror/lang-html': ^6.4.11
  '@codemirror/lang-javascript': ^6.2.4
  '@codemirror/lang-json': ^6.0.2
  '@codemirror/language': ^6.12.1
  '@codemirror/state': ^6.5.3
  '@codemirror/theme-one-dark': ^6.1.3
  '@codemirror/view': ^6.39.9
  codemirror: ^6.0.2

  # UI libraries
  '@tanstack/vue-virtual': ^3.13.6
  '@unocss/reset': ^66.5.12
  '@vue/devtools-ui': ^8.0.5
  floating-vue: ^5.2.2
  splitpanes: ^4.0.4
  unocss: ^66.5.12

  # Types
  '@types/node': ^25.0.3
  '@types/ws': ^8.18.1

  # Analysis tools
  knip: ^5.80.0

  #Docs
  vitepress: ^1.5.0
